### ISSUE TITLE
Visibility

### ISSUE THREAD

**Issue by ClearlyElevated** [papiersnipper/modmail-plugins#10]
How come this doesn't show up on the main sever but it lets your do it on inbox server? The main server is where it makes the most sense to have it show? Correct?

**Comment by papiersnipper** [comment]
I'm sorry, what exactly are you talking about?

**Comment by ClearlyElevated** [comment]
Only being able to have the bot respond to the `[p]support` in the mailbox guild.. but not in the main one

**Comment by papiersnipper** [comment]
This is due to how the internal logic of the plugin works. I might add a feature to choose your supporters in the future.
